### ISSUE TITLE
run error。。。

### ISSUE THREAD

**Issue by winner106** [acsysio/acsys#30]
![image](https://user-images.githubusercontent.com/50519642/102173503-191a2780-3ed6-11eb-9a84-9b944086b77c.png)
thanks buddy，but how to fix?

**Comment by cbridges1** [comment]
Hi, it looks like the API server never started. Do you have port 80 blocked?

**Comment by cbridges1** [comment]
I will go ahead and close this issue. The linked pull request contains the fix. The default port for the API server should now be 8080 instead of 80 which is blocked on some systems.
